image: archlinux
sources:
    - https://git.sr.ht/~ineptattech/aur-als-git
packages:
    - gprbuild-bootstrap
    - xmlada
    - git
    - python-e3-testsuite
tasks:
- prepare: |
    git clone https://aur.archlinux.org/gprbuild.git
    cd gprbuild
    makepkg
    yay -R --noconfirm gprbuild-bootstrap
    makepkg -i --noconfirm
    cd ..
    yay -S --answerclean=All --noconfirm xmlada
    # Grep the dependencies from the PKGBUILD and build them. Use positive look-behind and positive look-ahead.
    # Remove apostrophes from the match
    # TODO: This will fail if dependencies are split over multiple lines
    deps=$(grep --only-matching --perl-regexp "(?<=^depends=\()('\S+'\s*)+(?=\))" aur-als-git/PKGBUILD | tr --delete \')
    yay -S $deps --noconfirm
- build: |
    cd aur-als-git
    makepkg
- install: |
    cd aur-als-git
    makepkg --install --noconfirm
