image: archlinux
sources:
    - https://git.sr.ht/~ineptattech/aur-als
packages:
    - gprbuild-bootstrap
    - xmlada
    - git
    - python-e3-testsuite
tasks:
- prepare: |
    git clone https://aur.archlinux.org/gprbuild.git
    cd gprbuild
    makepkg
    yay -R --noconfirm gprbuild-bootstrap
    makepkg -i --noconfirm
    cd ..
    yay -S --answerclean=All --noconfirm xmlada
    yay -S libadalang-tools gtkada libvss ada_spawn ada-libfswatch gnatdoc gpr --noconfirm
- build: |
    cd aur-als
    makepkg
- install: |
    cd aur-als
    makepkg --install --noconfirm
