pipeline:
  build:
    image: archlinux/makepkg
    pull: true
    volumes:
      - /etc/makepkg.conf:/etc/makepkg.conf

  repoadd:
    image: archlinux/repoadd
    pull: true
    when:
      branch: master
    repo_name: archrepo
    repo_ownerid: 972
    repo_groupid: 971
    volumes:
      - /home/woodpecker/archrepo/:/repo/
