# * Prepare

image: archlinux

variables:
  DOSUDO: "notroot ALL=(ALL) NOPASSWD: ALL"

stages:
  - test

before_script:
  - pacman --noconfirm -Syu
  - pacman --noconfirm -S sudo git fakeroot binutils
  - useradd -m notroot
  - echo "$DOSUDO" > /etc/sudoers.d/notroot

# * Test

build-package:
  stage: test
  script:
    - su notroot -c "makepkg --noconfirm --syncdeps --rmdeps --install --clean"
    - python -c 'import cocotb; print("All OK")'
