image: "registry.devseed.de/all-the-things/docker-archlinux"

stages:
  - build
  - release


before_script:
  - sudo pacman -Sy --noconfirm pacman-contrib
  - git config --global user.email "${GIT_USER_EMAIL:-$GITLAB_USER_EMAIL}"
  - git config --global user.name "${GIT_USER_NAME:-$GITLAB_USER_NAME}"

update_hash:
  stage: build
  script:
    # update package hash for integrity check
    - updpkgsums

makepkg:
  stage: build
  script:
    # Test building a source package
    - sudo -u builder makepkg -C -S --log --noconfirm
    # Test building and installing the package
    - sudo -u builder makepkg -C -i --log --noconfirm

push:
  stage: release
  script:
    - git add PKGBUILD
    - git commit -m "updates hash for AppImage"
    - git push -o ci.skip "https://${GITLAB_USER_NAME}:${RENOVATE_TOKEN}@${CI_REPOSITORY_URL#*@}" "HEAD:${CI_COMMIT_BRANCH}"
