# * Prepare

image: archlinux/archlinux:base-devel

variables:
  DOSUDO: "notroot ALL=(ALL) NOPASSWD: ALL"

stages:
  - test

before_script:
  - pacman --noconfirm -Syu
  - useradd -m notroot
  - echo "$DOSUDO" > /etc/sudoers.d/notroot

# * Test

build-package:
  stage: test
  script:
    - su notroot -c "makepkg --noconfirm --syncdeps --rmdeps --install --clean"
    - python -c 'import cocotb; print("All OK")'
  artifacts:
    when: always
    paths:
      - python-cocotb-*.pkg.tar.zst
