stages:
  - test
  - build
  - install

namcap:
  stage: test
  image: docker.io/archlinux:latest
  before_script:
    - pacman -Syu --noconfirm namcap
  script:
    - namcap PKGBUILD

makepkg:
  stage: build
  image: docker.io/archlinux:base-devel
  before_script:
    - pacman -Syu --noconfirm sudo
    - useradd builduser -m && passwd -d builduser && printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers
  script:
    - sudo -u builduser bash -c 'makepkg -si --noconfirm'
  artifacts:
    paths:
      - "*.zst"
      - "/usr/sbin/yay"

pacman:
  stage: install
  image: docker.io/archlinux:latest
  dependencies:
    - makepkg
  before_script:
    - yay --noconfirm
  script:
    - yay -U --noconfirm *.zst
