image: archlinux:latest

variables:
  CHROOT: "$HOME/chroot"

build:
  script:
    - pacman --sync --refresh --needed --noconfirm --noprogressbar devtools
    - mkdir $CHROOT
    - mkarchroot $CHROOT/root base-devel
    - arch-nspawn $CHROOT/root pacman -Syu
    - makechrootpkg -c -r $CHROOT

