image: "registry.devseed.de/all-the-things/docker-archlinux"

stages:
  - test
  - update_hash
  - release


before_script:
  - sudo pacman -Sy --noconfirm pacman-contrib
  # Clone the repository via HTTPS inside a new directory
  - git clone "https://${GITLAB_USERNAME}:${GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git" "${CI_COMMIT_SHA}"
  # Set the displayed user with the commits that are about to be made
  - git config --global user.email "${GIT_USER_EMAIL:-$GITLAB_USER_EMAIL}"
  - git config --global user.name "${GIT_USER_NAME:-$GITLAB_USER_NAME}"

test:
  script:
    # update package hash for integrity check
    - updpkgsums
    # Test building a source package
    - sudo -u builder makepkg -C -S --log --noconfirm
    # Test building and installing the package
    - sudo -u builder makepkg -C -i --log --noconfirm

update_hash:
  script:
    - updpkgsums
    - git add PKGBUILD
    - git commit -m "updates hash for AppImage"
    - git push origin "${CI_DEFAULT_BRANCH}" -o ci.skip
