image: "imrehg/archlinux-makepkg"

before_script:
- sudo pacman -Syu --noconfirm
- yay --noconfirm -S r-e1071

package:
  script:
  - makepkg -s --noconfirm
  artifacts:
    paths:
    - pkg/
    - r-bsda-*.tar.xz
    expire_in: 2 days


