include:
  - project: "common/gitlab-helper"
    ref: master
    file: "ci-helper.yml"

workflow: !reference [ .common, workflow ]

variables:
  PKG_NAME: "gnudatalanguage"

stages:
  - containerize
  - build
  - test
  - deploy

container-build-and-test:
  extends: .arch-containerize
  needs: []

build-gnudatalanguage:
  artifacts:
    paths:
      - $PKG_NAME*.pkg.tar.zst
      - src/gdl-*/build/Testing/Temporary/LastTest.log
    when: always
  extends: .arch-buildx
  needs:
    - job: "container-build-and-test"
      artifacts: no
  
test-gnudatalanguage:
  extends: .arch-test
  needs: ["build-gnudatalanguage"]

deploy-gnudatalanguage:
  extends: .arch-deploy
