image: "registry.devseed.de/all-the-things/docker-archlinux"

before_script:
  - sudo pacman -Sy --noconfirm pacman-contrib
  - git config --global user.email "renovate@devseed.de"
  - git config --global user.name "Renovate Bot"

makepkg:
  script:
    # update package hash for integrity check
    - updpkgsums
    # Test building a source package
    - sudo -u builder makepkg -C -S --log --noconfirm
    # Test building and installing the package
    - sudo -u builder makepkg -C -i --log --noconfirm

update_hash:
  script:
    - updpkgsums
    - git add PKGBUILD
    - git commit -m "updates hash for AppImage"
    - git push
