build:
  stage: build
  image:
    name: countstarlight/makepkg:latest
    entrypoint: [""]
  before_script:
    - yay -Syu --noconfirm
  script:
    - |
      depends=()
      makedepends=()
      checkdepends=()
      . ./PKGBUILD
      deps=( "${depends[@]}" "${makedepends[@]}" "${checkdepends[@]}" )
      (pacman --deptest "${deps[@]}" || true) | xargs yay -Sy --noconfirm
    - makepkg -f
  artifacts:
    untracked: false
    expire_in: 5 days
    paths:
      - '*.pkg.tar.zst'
