stages:
  - test
  - build
  - install

namcap:
  stage: test
  image: docker.io/archlinux:latest
  before_script:
    - pacman -Syu --noconfirm namcap
  script:
    - namcap PKGBUILD

makepkg:
  stage: build
  image: docker.io/archlinux:base-devel
  before_script:
    - pacman -Syu --noconfirm sudo git
    - useradd builduser -m && passwd -d builduser && printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers
    - sudo -u builduser bash -c 'git clone "https://aur.archlinux.org/yay.git" && cd yay && makepkg -si --noconfirm'
    - rm -rf yay && cp $(which yay) yay
  script:
    - sudo -u builduser bash -c 'makepkg -s --noconfirm'
  artifacts:
    paths:
      - "$CI_PROJECT_NAME*.zst"
      - "yay"

pacman:
  stage: install
  image: docker.io/archlinux:latest
  dependencies:
    - makepkg
  before_script:
    - cp yay /usr/sbin/yay
    - useradd builduser -m && passwd -d builduser && printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers
    - sudo -u builduser bash -c 'yay --noconfirm'
  script:
    - sudo -u builduser bash -c 'yay -U --noconfirm *.zst'
