include:
  - project: 'archlinux-packages/ci-cd'
    ref: master
    file: 'github-packages.yml'

buildAndTest:
  script:
    - su gitlab -c 'makepkg --noconfirm --syncdeps --install .'
    - terraformer --version
