---
stages:
  - build

build:
  image:  archlinux/base
  only:
    - master
    - web
  script:
    - pacman -Sy --needed --noconfirm base-devel
    - useradd -m archie
    - su archie -c "makepkg $i"
  stage: build
  tags:
    - docker
