stages:
  - deploy

aur:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  variables:
    GIT_STRATEGY: clone
  image: docker.io/archlinux:latest
  before_script:
    - pacman -Syu --noconfirm socat openssh git
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY_B64" | base64 -d | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts 2>/dev/null && chmod 644 ~/.ssh/known_hosts
  script:
    - git checkout master
    - git remote add aur ssh://aur@aur.archlinux.org/$CI_PROJECT_NAME.git
    - git push -u aur master
    - sleep 30
