pages:
  image: archlinux/base
  stage: deploy
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - '*.pkg.tar.xz'
  before_script:
    - pacman -Sy --noconfirm --needed --noprogressbar archlinux-keyring
    - pacman -Sy --noconfirm --needed --noprogressbar sudo curl pacman ca-certificates
    - pacman -Sy --noconfirm --needed --noprogressbar base-devel namcap
    - pacman -Syu --noconfirm --needed --noprogressbar
    - pacman-db-upgrade
    - update-ca-trust
    - useradd -m -G wheel build
    - chgrp -R build .
    - 'echo -e "Cmnd_Alias\tBUILDERS = /usr/sbin/pacman, /usr/sbin/makepkg, /usr/bin/pacman, /usr/bin/makepkg, /usr/bin/multilib-build, /usr/bin/extra-x86_64-build, /usr/bin/arch-nspawn\nbuild\tALL = NOPASSWD: BUILDERS" >> /etc/sudoers.d/build'
    - chmod 0440 /etc/sudoers.d/build
    - chown root:root /etc/sudoers.d/build

  script:
    - sudo -u build makepkg --log --syncdeps --force --noconfirm --noprogressbar
    - 'find . -iname "*.pkg.tar.xz" -exec namcap --machine-readable {} \;'
