mksrcinfo:
  image: archlinux:latest
  stage: build
  before_script:
    - groupadd -r makepkg
    - useradd -u 1000 -g makepkg -m makepkg
    - su -u makepkg makepkg --printsrcinfo
    - pacman -Sy --noconfirm base base-devel
  script:
    - makepkg -- makepkg --printsrcinfo

publish:
  image: archlinux:latest
  stage: deploy
  before_script:
    - pacman -Sy git
  script:
    - git remote add aur ssh://aur@aur.archlinux.org/$CI_PROJECT_NAME
    - git push aur master
