language: ruby
before_install:
- openssl aes-256-cbc -K $encrypted_0727dd33f742_key -iv $encrypted_0727dd33f742_iv
  -in id_rsa.enc -out id_rsa -d
script:
  - mkdir -p ~/.ssh
  - echo -e "Host aur.archlinux.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - mv id_rsa ~/.ssh/
  - chmod 600 ~/.ssh/id_rsa
  - git remote add aur git+ssh://aur@aur.archlinux.org/home-assistant.git
  - git push aur HEAD:master
