language: generic
services:
  - docker
install:
  - docker run -d --name -v $(pwd):/root/pkg arch base/devel bash
script:
  - export latestRelease=$(curl --silent "https://api.github.com/repos/roboll/helmfile/releases/latest" | grep -Po '"tag_name": "v\K.*?(?=")')
  - sed -i "s/pkgver=.*/pkgver=$latestRelease/" ./PKGBUILD
  - docker exec arch -w /root/pkg /bin/bash -c "makepkg --printsrcinfo > .SRCINFO"
  - docker exec arch -w /root/pkg /bin/bash -c "makepkg"
  - git status