language: minimal
dist: xenial
sudo: no
services:
  - docker

branches:
  only:
    - aur

install:
  # pull base-devel container and prepare build user
  - docker run --name arch -v $PWD:/source -d -t antergos/archlinux-base-devel bash
  - docker exec -t arch useradd -m -G wheel -k /dev/null builder
  - "docker exec -t arch bash -c 'echo \"%wheel ALL=(ALL) NOPASSWD: ALL\" > /etc/sudoers'"
  - docker exec -t arch cp -rT /source /home/builder

script:
  # make package, install and test version output
  - docker exec -t arch su -l builder -c 'yes | makepkg -s'
  - docker exec -t arch bash -c 'yes | pacman -U ~builder/*.pkg.tar.*'
  - docker exec -t arch aenker --version
  # check if the SRCINFO is properly updated
  - docker exec -t arch su -l builder -c 'diff -u .SRCINFO <(makepkg --printsrcinfo)'

after_script:
  - docker rm -f arch

env:
  global:
    # encrypted deployment key
    secure: hryqiygh+qC4gGDmybYUlavKdW/iqBZ1vIYljhWXVOgyeZK/UtbQ5v9I5t2txmlm429gSJR/kiZJqFaEf7E0Sk/wwDT69NBTUDucf194P7G+36RQgTuRt3iFFQfeFwvTwuyOY+LPvp5K2BOSkow1mir6WgqyDM7CML0qP/F+JDUyKWfIcFfsCJIIqSeF5Vp1+aIgqtd3Wi0614haQd03dlGpS1rW1iPxv7E+OhW7eyKaRg6K7OhMEULOakFNAgAHMpdv2lFGk1nqpHq3a+0FHEXtG5fN0SG8btSnimyYf6RTmAOHwuRqyR2aTtLuXBTVVGCLsSQjhIIye/4jgqcRvVCtuv2jf7Z+AGqi1m8K5QPraTQvN+XHBvfDWZ6kD0Upr8e70KlotFsK8y32L49H+bmYDBKYlFbZUfHNS4xaAOmjTM+4K510ivAUcyxdHg5bRMxAbit84xakKftcg09/Et821gISbZoqXEyiAML69OF+zNiQu05eUuy6KI4d8sWFFnEQA5LzjT9BYju9gFoE3pd/+Q5d5kcG3j+6VZ32TS/4zXfIdEsjYPCEVcUJcz/yc9lQs3ojHKRJVI8KnzqDLeO6T5gZ8oTx0p8rjpMeU1ld7frK13WrKWXa5Uf0xTyiTlJvAf8rM+FUbnycj2aY+Q8pxXygg3QnHlqTvH4KhfY=

before_deploy:
  # insert aur hostkey and our deployment key
  - echo "aur.archlinux.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM2DCBtPSTwWvBU3/3bAYwJVtnAmy+GEJf98Ek5QhOXh" >> ~/.ssh/known_hosts
  - echo "$deployment_key" | base64 -d | gunzip > ~/.ssh/deploy
  - chmod 600 ~/.ssh/deploy

deploy:
  # push to AUR
  provider: script
  script: GIT_SSH_COMMAND="ssh -v -i ~/.ssh/deploy" git push ssh://aur@aur.archlinux.org/aenker.git aur:master
  on:
    all_branches: yes
