log_level = "Error"
cards = ["card0"]

[[speed_matrix]]
temp = 4.0
speed = 4

[[speed_matrix]]
temp = 30.0
speed = 33

[[speed_matrix]]
temp = 45.0
speed = 50

[[speed_matrix]]
temp = 60.0
speed = 66

[[speed_matrix]]
temp = 65.0
speed = 69

[[speed_matrix]]
temp = 70.0
speed = 75

[[speed_matrix]]
temp = 75.0
speed = 89

[[speed_matrix]]
temp = 80.0
speed = 100
