flags: {}
extra-package-dbs: []
packages:
- '.'

extra-deps:
- ConfigFile-1.1.4
- broadcast-chan-0.2.1.1
- dbus-1.2.21
- dbus-hslogger-0.1.0.1
# gtk-sni-tray for a clean tray
- gtk-sni-tray-0.1.8.0
# GTK3 for my-taffybar
- gtk3-0.15.5
# For gtk3
- cairo-0.13.8.1
- gio-0.13.8.1
- glib-0.13.8.1
- gtk2hs-buildtools-0.13.8.0
- pango-0.13.8.1

# From base taffybar
- gi-glib-2.0.25
- haskell-gi-0.25.0
- haskell-gi-base-0.25.0
# From manual "finding out the package and finding the most recent version"
- gi-cairo-connector-0.1.0
- gi-cairo-render-0.1.0
- gi-cairo-1.0.25
- gi-gmodule-2.0.1
- gi-pango-1.0.24
- gi-gtk-hs-0.3.10
# Seeing that theoretically the `g_spec_param_uref` linking issue has been fixed,
# gi-gobject is fixed to the most recent version
# Source : https://github.com/haskell-gi/haskell-gi/issues/298 and
#   https://github.com/haskell-gi/haskell-gi/issues/301
- gi-gobject-2.0.26
- gi-gio-2.0.28
# From gi-pango
- gi-harfbuzz-0.0.4
- gi-dbusmenu-0.4.9
- gi-dbusmenugtk3-0.4.10
- gi-gdkx11-3.0.11
- gi-xlib-2.0.10
- gtk-strut-0.1.3.0
- rate-limit-1.4.1
- status-notifier-item-0.3.1.0
- time-units-1.0.0
- xml-helpers-1.0.0
- safe-0.3.19
- MissingH-1.4.3.0
- xdg-desktop-entry-0.1.1.1



resolver: lts-18.5
allow-newer: true
ghc-options:
  $everything: -split-sections -haddock
  $locals: -fwrite-ide-info -hiedir=.hie -fmax-relevant-binds=0
